/*
USE BETTER COMMENTS EXTENSION IN VS CODE TO MAKE THIS FILE MORE READABLE

THE GAME WILL USE SAME VALUES AGAIN AND AGAIN
note WE WILL USE THESE AS CONSTANTS REDUCING THE ERRORS BY MISTYPING
*/

import { getDelay } from '../utils';

// asset keys for images and sounds
export const BULLET_KEY = 'bullet';
export const PLAYER_KEY = '295';

// player constants
export const PLAYER_SCALE = 0.4;
export const PLAYER_ROTATION = 200;
export const PLAYER_DRAG = 100;
export const PLAYER_VELOCITY = 200;
export const PLAYER_ORIGIN_X = 0.4;
export const PLAYER_ORIGIN_Y = 0.5;
// specify the number of bullets per second
const PLAYER_FIRE_RATE_INTERNAL_LEVEL1 = 3;
const PLAYER_FIRE_RATE_INTERNAL_LEVEL2 = 5;
const PLAYER_FIRE_RATE_INTERNAL_LEVEL3 = 10;
const PLAYER_FIRE_RATE_INTERNAL_LEVEL4 = 20;
const PLAYER_FIRE_RATE_INTERNAL_LEVEL5 = 30;

// convert fire rate to milliseconds
// default fire rate
export const PLAYER_FIRE_RATE = getDelay(PLAYER_FIRE_RATE_INTERNAL_LEVEL1);
export const PLAYER_FIRE_RATE_LEVEL2 = getDelay(PLAYER_FIRE_RATE_INTERNAL_LEVEL2);
export const PLAYER_FIRE_RATE_LEVEL3 = getDelay(PLAYER_FIRE_RATE_INTERNAL_LEVEL3);
export const PLAYER_FIRE_RATE_LEVEL4 = getDelay(PLAYER_FIRE_RATE_INTERNAL_LEVEL4);
export const PLAYER_FIRE_RATE_LEVEL5 = getDelay(PLAYER_FIRE_RATE_INTERNAL_LEVEL5);

export const PLAYER_MAX_VELOCITY = 300;
export const PLAYER_SPEED = 200;

/*
IN THE GAME: 
- WE WILL HAVE SEVERAL TYPES OF BULLETS
THE ORIGINAL CLASS WILL ALWAYS BE BULLET BUT 
THE PROPERTIES WILL BE DIFFERENT

PROPERTIES MAY INCLUDE:
- KEY, LIFE, SCALE, SPEED ETC.
*/

// bullet constants

// basic bullet constants
export const BULLET_SPEED = 300;
export const MAX_BULLETS = 10;
export const BULLET_LIFE = 1000;
export const BULLET_SCALE = 0.3;
